# Generated by Django 5.2.14 on 2026-05-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antannotation',
            options={'ordering': ['label'], 'verbose_name': 'annotation fourmi', 'verbose_name_plural': 'annotations fourmis'},
        ),
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'image utilisateur', 'verbose_name_plural': 'images utilisateurs'},
        ),
        migrations.AlterField(
            model_name='antannotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='antannotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='counter.userimage', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='antannotation',
            name='label',
            field=models.PositiveIntegerField(verbose_name='étiquette'),
        ),
        migrations.AlterField(
            model_name='antannotation',
            name='x',
            field=models.FloatField(verbose_name='coordonnée X'),
        ),
        migrations.AlterField(
            model_name='antannotation',
            name='y',
            field=models.FloatField(verbose_name='coordonnée Y'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='hauteur'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='species',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='espèce'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='uploadé le'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='largeur'),
        ),
        migrations.CreateModel(
            name='ModelTrainingPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('species', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_pics', to='counter.userimage')),
            ],
            options={
                'verbose_name': "image d'entraînement",
                'verbose_name_plural': "images d'entraînement",
            },
        ),
    ]
